# Generated by Django 6.0.1 on 2026-02-25 20:44

import api.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='DefaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Default Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mock_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FileStructureMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_column_name', models.CharField(blank=True, help_text='The header name in the CSV that corresponds to the transaction description.', max_length=255, null=True)),
                ('income_amount_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True)),
                ('expense_amount_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True)),
                ('date_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction date.', max_length=255, null=True)),
                ('merchant_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the merchant or payee name.', max_length=255, null=True)),
                ('operation_type_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the operation type.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Agent description of the csv structure')),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row_hash',), name='unique_user_transaction_row')],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', api.fields.EncryptedCharField(blank=True, db_column='name', null=True)),
                ('name_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuzzy_search_trigrams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MerchantEMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_footprint', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_structure_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_emas', to='api.filestructuremetadata')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emas', to='api.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(default='free_trial', max_length=50)),
                ('onboarding_step', models.IntegerField(default=1, help_text='1: Categories, 2: Upload, 3: Filters, 4: Personalize, 5: Completed')),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='Rule Text')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='api.category')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_column_name', models.CharField(blank=True, help_text='The header name in the CSV that corresponds to the transaction description.', max_length=255, null=True)),
                ('income_amount_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True)),
                ('expense_amount_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True)),
                ('date_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction date.', max_length=255, null=True)),
                ('merchant_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the merchant or payee name.', max_length=255, null=True)),
                ('operation_type_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the operation type.', max_length=255, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the mapping record was created/uploaded.')),
                ('dimension', models.PositiveBigIntegerField(blank=True, help_text='The size of the associated CSV file in bytes.', null=True)),
                ('processing_time', models.IntegerField(blank=True, help_text='The time taken to process the associated CSV file (in milliseconds).', null=True)),
                ('file_name', models.CharField(blank=True, help_text='The file name', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Agent description of the csv structure')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=70)),
                ('file_structure_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_files', to='api.filestructuremetadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_maps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=20)),
                ('operation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('amount', api.fields.EncryptedDecimalField(blank=True, db_column='amount', null=True)),
                ('description', api.fields.EncryptedCharField(blank=True, db_column='description', null=True)),
                ('description_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('categorized', 'Categorized'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('manual_insert', models.BooleanField(default=False)),
                ('modified_by_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict, null=True)),
                ('categorized_by_agent', models.BooleanField(default=False)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.category')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('upload_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.uploadfile')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YearlyMonthlyUserRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_year', models.IntegerField()),
                ('total_amount_expense_by_year', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('total_amount_income_by_year', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('total_amount_expense_by_month', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('total_amount_income_by_month', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('month_number', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_rollups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yearly Monthly User Rollup',
                'verbose_name_plural': 'Yearly Monthly User Rollups',
            },
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['user', 'name_hash'], name='api_merchan_user_id_0d991a_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fuzzy_search_trigrams'], name='api_merchan_fuzzy_s_342e37_gin'),
        ),
        migrations.AddIndex(
            model_name='merchantema',
            index=pgvector.django.indexes.HnswIndex(fields=['digital_footprint'], name='merchant_ema_footprint_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['user', 'is_active'], name='api_rule_user_id_421174_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', '-transaction_date', '-created_at'], name='api_transac_user_id_372084_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='api_transac_user_id_085b42_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'merchant'], name='api_transac_user_id_0001a1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'description_hash'], name='api_transac_user_id_bcf47f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='api_transac_status_0f4e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='api_transac_user_id_daa5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='idx_tx_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='yearlymonthlyuserrollup',
            unique_together={('user', 'by_year', 'month_number')},
        ),
    ]
