# Generated by Django 5.2.7 on 2025-10-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='validity_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='validity_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
