# Generated by Django 5.2.8 on 2025-11-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '00002_summary_view'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinancialSummary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='financial_summary', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_spending', models.DecimalField(decimal_places=2, help_text='Total amount spent across all categorized expenses', max_digits=10)),
                ('monthly_average_spending', models.DecimalField(decimal_places=2, help_text='Average spending per active month', max_digits=10)),
                ('top_category_id', models.IntegerField(blank=True, help_text='ID of the category with highest spending', null=True)),
                ('top_category_name', models.CharField(blank=True, help_text='Name of the top spending category', max_length=100, null=True)),
                ('top_category_spending', models.DecimalField(decimal_places=2, help_text='Top category total expenses amount', max_digits=10)),
                ('top_category_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total spending for top category', max_digits=10)),
            ],
            options={
                'verbose_name': 'User Financial Summary',
                'verbose_name_plural': 'User Financial Summaries',
                'db_table': 'user_financial_summary',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='normalized_description',
            field=models.TextField(null=True),
        ),
    ]
