# Generated by Django 5.2.7 on 2025-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rule_validity_end_date_rule_validity_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failure_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
