# Generated by Django 5.2.8 on 2025-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userfinancialsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categorized_by_agent',
            field=models.BooleanField(default=False),
        ),
    ]
