# Generated by Django 5.2.7 on 2025-10-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_failure_code_transaction_raw_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
