# Generated by Django 5.2.8 on 2025-11-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_categorized_by_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
