# Generated by Django 5.2.8 on 2025-11-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merchant_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='notes',
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
