# Generated by Django 5.2.7 on 2025-10-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='api.category'),
        ),
        migrations.AddField(
            model_name='rule',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.merchant'),
        ),
    ]
