# Generated by Django 5.2.7 on 2025-10-29 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rule_category_rule_merchant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVHeaderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_header', models.CharField(help_text='Original CSV column header name', max_length=255)),
                ('target_field', models.CharField(choices=[('amount', 'Amount'), ('date', 'Date'), ('description', 'Description')], help_text='Target field to map the CSV column to', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_header_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_field', 'csv_header'],
                'indexes': [models.Index(fields=['user', 'target_field'], name='api_csvhead_user_id_cc842b_idx')],
                'unique_together': {('user', 'csv_header')},
            },
        ),
    ]
