# Generated by Django 5.2.8 on 2025-11-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_merchant_notes_transaction_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
        migrations.AddField(
            model_name='csvupload',
            name='notes',
            field=models.TextField(blank=True, help_text='Agent description of the csv structure'),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='operation_type_column_name',
            field=models.CharField(blank=True, help_text='The header name in the CSV for the operation type.', max_length=255, null=True),
        ),
    ]
