# Generated by Django 5.2.8 on 2025-12-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_transaction_notes_csvupload_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='file_name',
            field=models.CharField(blank=True, help_text='The file name', max_length=255, null=True),
        ),
    ]
