# Generated by Django 5.2.7 on 2025-10-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_csvheadermapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVHeaderMapping',
        ),
    ]
