# Generated by Django 5.2.7 on 2025-10-31 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_csvheadermapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='validity_end_date',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='validity_start_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CsvUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_column_name', models.CharField(blank=True, help_text='The header name in the CSV that corresponds to the transaction description.', max_length=255, null=True)),
                ('amount_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True)),
                ('date_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction date.', max_length=255, null=True)),
                ('merchant_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the merchant or payee name.', max_length=255, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the mapping record was created/uploaded.')),
                ('dimension', models.PositiveBigIntegerField(blank=True, help_text='The size of the associated CSV file in bytes.', null=True)),
                ('processing_time', models.IntegerField(blank=True, help_text='The time taken to process the associated CSV file (in milliseconds).', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_maps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='csv_upload',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.csvupload'),
            preserve_default=False,
        ),
    ]
