# Generated by Django 5.2.8 on 2025-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_monthly_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMonthlySummary',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'category_id', 'year', 'month', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Zero-Filled Monthly Summary',
                'db_table': 'category_monthly_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
                ('transaction_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Monthly Financial Summary',
                'db_table': 'monthly_financial_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Default Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='default_categories',
        ),
    ]
