
# Generated by Django 5.2.8

from django.db import migrations


DEFAULT_CATEGORIES = [
    # Casa e Abitazione
    ("Affitto/Mutuo", "Canone di locazione o rata del mutuo"),
    ("Bollette Energia", "Luce, gas, riscaldamento"),
    ("Bollette Acqua", "Servizio idrico"),
    ("Internet e Telefono", "Connessione internet, linea fissa, mobile"),
    ("Condominio", "Spese condominiali, amministrazione"),
    ("Manutenzione Casa", "Riparazioni, manutenzione ordinaria e straordinaria"),
    ("Tasse Casa", "TARI, IMU e altre tasse immobiliari"),

    # Alimentari
    ("Supermercato", "Spesa alimentare e prodotti per la casa"),
    ("Frutta e Verdura", "Mercato, fruttivendolo"),
    ("Panetteria", "Pane, prodotti da forno"),
    ("Macelleria e Pescheria", "Carne e pesce freschi"),
    ("Alimentari Specializzati", "Prodotti biologici, specialità, etnici"),

    # Mangiare Fuori
    ("Bar e Colazioni", "Caffè, colazioni, pasticceria"),
    ("Pranzi Veloci", "Panini, tavola calda, street food"),
    ("Ristoranti", "Cene e pranzi al ristorante"),
    ("Pizzeria", "Pizza da asporto o in pizzeria"),
    ("Delivery", "JustEat, Glovo, Deliveroo, Uber Eats"),
    ("Aperitivi", "Aperitivi e happy hour"),

    # Trasporti
    ("Carburante", "Benzina, diesel, GPL"),
    ("Mezzi Pubblici", "Abbonamenti, biglietti bus/metro/tram"),
    ("Treni", "Biglietti treno, abbonamenti ferroviari"),
    ("Taxi e Ride-sharing", "Taxi, Uber, Bolt"),
    ("Parcheggi e Pedaggi", "Sosta, parcheggi, autostrada"),
    ("Auto - Manutenzione", "Tagliandi, riparazioni, pneumatici"),
    ("Auto - Assicurazione", "RCA e altre polizze veicolo"),
    ("Auto - Bollo", "Tassa automobilistica"),

    # Shopping
    ("Abbigliamento", "Vestiti, scarpe, accessori"),
    ("Elettronica", "Smartphone, PC, tablet, accessori tech"),
    ("Casa e Arredamento", "Mobili, complementi d'arredo, decorazioni"),
    ("Libreria e Cartoleria", "Libri, quaderni, cancelleria"),
    ("Regali", "Regali per altri"),
    ("Shopping Online", "Acquisti online non categorizzati"),

    # Salute e Benessere
    ("Farmacia", "Farmaci, parafarmaci, integratori"),
    ("Visite Mediche", "Medico di base, specialisti"),
    ("Dentista", "Cure odontoiatriche"),
    ("Parrucchiere/Barbiere", "Taglio, piega, trattamenti capelli"),
    ("Estetista", "Trattamenti estetici, manicure, pedicure"),
    ("Palestra", "Abbonamenti, corsi fitness"),
    ("Sport", "Attrezzatura sportiva, corsi, attività"),
    ("Benessere", "Massaggi, spa, wellness"),

    # Tempo Libero
    ("Cinema e Teatro", "Biglietti, spettacoli"),
    ("Concerti ed Eventi", "Concerti, festival, eventi live"),
    ("Streaming", "Netflix, Prime Video, Disney+, etc."),
    ("Musica", "Spotify, Apple Music, etc."),
    ("Vacanze", "Viaggi, hotel, voli"),
    ("Weekend", "Gite fuori porta, escursioni"),
    ("Hobby", "Materiali e attività per hobby"),
    ("Animali Domestici", "Pet food, veterinario, toelettatura"),

    # Famiglia e Istruzione
    ("Scuola", "Rette scolastiche, tasse"),
    ("Asilo/Nido", "Rette asilo nido o scuola dell'infanzia"),
    ("Università", "Tasse universitarie, libri accademici"),
    ("Corsi e Formazione", "Corsi professionali, lingue, aggiornamento"),
    ("Baby-sitter", "Servizi di assistenza bambini"),
    ("Assistenza Anziani", "Badanti, servizi per anziani"),
    ("Materiale Scolastico", "Libri di testo, zaini, materiale didattico"),

    # Finanza e Servizi
    ("Commissioni Bancarie", "Costi conto corrente, operazioni bancarie"),
    ("Assicurazioni Vita/Casa", "Polizze vita, casa, infortuni"),
    ("Bolli e Tasse", "Bolli statali, tasse varie"),
    ("Professionisti", "Commercialista, avvocato, notaio"),
    ("Prestiti Personali", "Rate finanziamenti, prestiti"),

    # Altro
    ("Beneficenza", "Donazioni, ONLUS, beneficenza"),
]


def seed_default_categories(apps, schema_editor):
    """
    Populate DefaultCategory with detailed categories.
    Idempotent - safe to run multiple times.
    """
    DefaultCategory = apps.get_model("api", "DefaultCategory")

    for name, description in DEFAULT_CATEGORIES:
        DefaultCategory.objects.update_or_create(
            name=name,
            defaults={'description': description}
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded categories on rollback."""
    DefaultCategory = apps.get_model("api", "DefaultCategory")
    category_names = [name for name, _ in DEFAULT_CATEGORIES]
    DefaultCategory.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_categorymonthlysummary_monthlysummary_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_categories, reverse_code=reverse_seed),
    ]