
# Generated by Django 5.2.8

from django.db import migrations



DEFAULT_CATEGORIES = [
    # Casa e Abitazione
    ("Affitto/Mutuo", "Canone di locazione o rata del mutuo per l'abitazione principale o secondaria"),
    ("Utenze", "Bollette di luce, gas, acqua, riscaldamento e servizio idrico"),
    ("Internet e Telefono", "Connessione internet, linea fissa, abbonamenti mobile"),
    ("Casa - Spese e Manutenzione", "Spese condominiali, TARI, IMU, tasse immobiliari, riparazioni, manutenzione ordinaria e straordinaria"),

    # Alimentari
    ("Spesa Alimentare", "Supermercato, frutta e verdura, pane, carne, pesce, mercato, prodotti biologici e specializzati"),

    # Mangiare Fuori
    ("Bar e Caffè", "Caffè, colazioni, pasticceria, aperitivi, happy hour"),
    ("Ristoranti e Pranzi Fuori", "Ristoranti, pizzeria, pranzi veloci, panini, tavola calda, street food, delivery (JustEat, Glovo, Deliveroo, Uber Eats)"),

    # Trasporti
    ("Carburante", "Benzina, diesel, GPL, metano"),
    ("Trasporti e Spostamenti", "Abbonamenti e biglietti bus, metro, tram, treni, ferrovie, taxi, Uber, Bolt, car sharing, ride-sharing"),
    ("Auto - Gestione", "Assicurazione RCA, bollo auto, parcheggi, pedaggi autostradali, manutenzione, tagliandi, riparazioni, pneumatici"),

    # Shopping
    ("Abbigliamento", "Vestiti, scarpe, accessori moda"),
    ("Elettronica", "Smartphone, PC, tablet, accessori tecnologici, elettronica di consumo"),
    ("Casa e Arredamento", "Mobili, complementi d'arredo, decorazioni, articoli per la casa"),
    ("Libri e Cartoleria", "Libri, ebook, quaderni, cancelleria, materiale da scrittura"),
    ("Shopping Online", "Acquisti online generici non categorizzati"),
    ("Regali", "Regali per altri, occasioni speciali, compleanni, ricorrenze"),

    # Salute e Benessere
    ("Salute", "Farmaci, parafarmaci, integratori, visite mediche, specialisti, dentista, cure odontoiatriche"),
    ("Cura Personale", "Parrucchiere, barbiere, estetista, trattamenti estetici, manicure, pedicure"),
    ("Sport e Fitness", "Palestra, abbonamenti fitness, corsi sportivi, attrezzatura sportiva, attività sportive, massaggi, spa, wellness"),

    # Tempo Libero
    ("Intrattenimento Fuori Casa", "Cinema, teatro, concerti, festival, eventi live, spettacoli"),
    ("Abbonamenti Digitali", "Netflix, Prime Video, Disney+, Spotify, Apple Music, servizi streaming"),
    ("Viaggi e Vacanze", "Viaggi, hotel, voli, gite fuori porta, weekend, escursioni"),
    ("Hobby e Passioni", "Materiali e attività per hobby personali"),
    ("Animali Domestici", "Pet food, veterinario, toelettatura, accessori e cure per animali"),

    # Famiglia e Istruzione
    ("Istruzione", "Rette scolastiche, asilo nido, scuola dell'infanzia, tasse universitarie, libri accademici, materiale scolastico, libri di testo, zaini"),
    ("Corsi e Formazione", "Corsi professionali, lingue straniere, formazione, aggiornamento professionale"),
    ("Assistenza Familiare", "Baby-sitter, badanti, servizi di assistenza bambini e anziani"),

    # Finanza e Servizi
    ("Servizi Bancari e Assicurativi", "Commissioni bancarie, costi conto corrente, assicurazioni vita, casa, infortuni"),
    ("Tasse e Professionisti", "Bolli statali, tasse varie, commercialista, avvocato, notaio, consulenti"),
    ("Finanziamenti", "Rate finanziamenti, prestiti personali, rate acquisti"),

    # Altro
    ("Beneficenza", "Donazioni, ONLUS, contributi benefici, charity"),
]


def seed_default_categories(apps, schema_editor):
    """
    Populate DefaultCategory with detailed categories.
    Idempotent - safe to run multiple times.
    """
    DefaultCategory = apps.get_model("api", "DefaultCategory")

    for name, description in DEFAULT_CATEGORIES:
        DefaultCategory.objects.update_or_create(
            name=name,
            defaults={'description': description}
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded categories on rollback."""
    DefaultCategory = apps.get_model("api", "DefaultCategory")
    category_names = [name for name, _ in DEFAULT_CATEGORIES]
    DefaultCategory.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_categorymonthlysummary_monthlysummary_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_categories, reverse_code=reverse_seed),
    ]