# Generated by Django 5.2.8 on 2025-12-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_seed_default_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvupload',
            old_name='amount_column_name',
            new_name='expense_amount_column_name',
        ),
        migrations.AddField(
            model_name='csvupload',
            name='income_amount_column_name',
            field=models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True),
        ),
    ]
