# Generated by Django 5.2.8 on 2025-12-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_amount_column_name_csvupload_expense_amount_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
