# Generated by Django 5.2.8 on 2025-12-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transaction_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_raw_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
