# Generated by Django 5.2.8
from os import name

from django.db import migrations

CATEGORY_TO_DELETE = ("Elettronica", "Smartphone, PC, tablet, accessori tecnologici, elettronica di consumo")
CATEGORY_TO_UPDATE = ("Shopping Online", "Acquisti ecommerce online")
PREVIOUS_DESCRIPTION = "Acquisti online generici non categorizzati"


def seed_default_categories(apps, schema_editor):
    """
    Populate DefaultCategory with detailed categories.
    Idempotent - safe to run multiple times.
    """
    DefaultCategory = apps.get_model("api", "DefaultCategory")

    DefaultCategory.objects.filter(name=CATEGORY_TO_UPDATE[0]).update(
        description=CATEGORY_TO_UPDATE[1]
    )
    DefaultCategory.objects.filter(name=CATEGORY_TO_DELETE[0]).delete()


def reverse_seed(apps, schema_editor):
    """Remove seeded categories on rollback."""
    DefaultCategory = apps.get_model("api", "DefaultCategory")
    DefaultCategory.objects.filter(name=CATEGORY_TO_UPDATE[0]).update(
        description=PREVIOUS_DESCRIPTION
    )
    DefaultCategory(name=CATEGORY_TO_DELETE[0], description=CATEGORY_TO_DELETE[1]).save()

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_alter_transaction_merchant_raw_name_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_categories, reverse_code=reverse_seed),
    ]
