# Generated by Django 5.2.8 on 2025-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
    ]
