# Generated by Django 5.2.8 on 2025-12-27 16:48

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_modify_internal_bank_transfer')
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_user_id_fc7bd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_merchan_bb3a78_idx',
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['user', 'name'], name='api_merchan_user_id_83401b_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['user', 'normalized_name'], name='api_merchan_user_id_b93138_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='merchant_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_name'], name='merchant_norm_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', '-transaction_date', '-created_at'], name='api_transac_user_id_372084_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='api_transac_user_id_085b42_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'merchant'], name='api_transac_user_id_0001a1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'amount'], name='api_transac_user_id_2c29bd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='api_transac_user_id_daa5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['merchant_raw_name'], name='trans_merch_raw_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='trans_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
