# Generated by Django 5.2.8 on 2025-12-28 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_internalbanktransfer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalBankTransfer',
            fields=[
                ('income_transaction', models.OneToOneField(db_column='income_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='internal_transfer_in', serialize=False, to='api.transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('income_date', models.DateField()),
                ('expense_transaction', models.ForeignKey(db_column='expense_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_transfer_out', to='api.transaction')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Bank Transfer',
                'verbose_name_plural': 'Internal Bank Transfers',
            },
        ),
    ]
