# Generated by Django 5.2.8 on 2025-12-28 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_internalbanktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalbanktransfer',
            name='expense_date',
        ),
        migrations.RemoveField(
            model_name='internalbanktransfer',
            name='income_date',
        ),
        migrations.AlterField(
            model_name='internalbanktransfer',
            name='expense_transaction',
            field=models.ForeignKey(db_column='expense_id', on_delete=django.db.models.deletion.CASCADE, related_name='internal_transfer_out', to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='internalbanktransfer',
            name='income_transaction',
            field=models.OneToOneField(db_column='income_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='internal_transfer_in', serialize=False, to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='internalbanktransfer',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='internal_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
