# Generated by Django 5.2.8 on 2025-12-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_drop_internal_bank_transfer_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalbanktransfer',
            name='expense_transaction',
            field=models.OneToOneField(db_column='expense_id', on_delete=django.db.models.deletion.CASCADE, related_name='internal_transfer_out', to='api.transaction'),
        ),
    ]
