# Generated by Django 5.2.8 on 2025-12-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_internalbanktransfer_expense_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalBankTransfer',
        ),
    ]
