# Generated by Django 5.2.8 on 2026-01-11 14:50

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('api', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user, defaults={'subscription_type': 'free_trial'})

def reverse_profiles(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, reverse_profiles),
    ]
