# Generated by Django 5.2.8 on 2026-01-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_populate_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=70),
        ),
    ]
