# Generated by Django 5.2.8 on 2026-01-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_csvupload_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_info', to='api.csvupload')),
            ],
        ),
    ]
