# Generated by Django 5.2.8 on 2026-01-16 10:35

from django.db import migrations

def update_upload_file_status(apps, schema_editor):
    CsvUpload = apps.get_model('api', 'CsvUpload')
    Transaction = apps.get_model('api', 'Transaction')
    
    # Iterate over all CsvUploads that are not already completed
    for upload in CsvUpload.objects.exclude(status='completed'):
        # Check if all related transactions are categorized or reviewed
        # We also ensure there is at least one transaction to avoid marking 
        # brand new/empty uploads as completed.
        transactions = Transaction.objects.filter(upload_file=upload)
        
        if transactions.exists():
            # If there are NO transactions that are NOT categorized/reviewed,
            # then ALL transactions are categorized/reviewed.
            has_non_categorized = transactions.exclude(status__in=['categorized']).exists()
            
            if not has_non_categorized:
                upload.status = 'completed'
                upload.save()

def reverse_update_upload_file_status(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_uploadresume'),
    ]

    operations = [
        migrations.RunPython(update_upload_file_status, reverse_update_upload_file_status),
    ]
