# Generated by Django 5.2.8 on 2026-01-16 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_update_upload_file_status'),
        ('costs', '0005_apiusagelog_final_earning_apiusagelog_input_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsvUpload',
            new_name='UploadFile',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='upload_file',
            new_name='upload_file',
        ),
        migrations.RenameField(
            model_name='uploadresume',
            old_name='upload_file',
            new_name='upload_file',
        ),
    ]
