# Generated by Django 5.2.8 on 2026-01-16 17:30

from django.db import migrations, connection

def rename_column_if_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        # Check if api_transaction table has csv_upload_id column
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'api_transaction' AND column_name = 'csv_upload_id'
        """)
        if cursor.fetchone():
            print("Renaming csv_upload_id to upload_file_id in api_transaction table...")
            cursor.execute("ALTER TABLE api_transaction RENAME COLUMN csv_upload_id TO upload_file_id")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_csvupload_uploadfile_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_column_if_exists, migrations.RunPython.noop),
    ]
