# Generated by Django 5.2.8 on 2026-01-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_fix_uploadresume_upload_file_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_step',
            field=models.IntegerField(default=1, help_text='1: Categories, 2: Upload, 3: Filters, 4: Completed'),
        ),
    ]
