# Generated by Django 5.2.8 on 2026-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_profile_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='onboarding_step',
            field=models.IntegerField(default=1, help_text='1: Categories, 2: Upload, 3: Filters, 4: Personalize, 5: Completed'),
        ),
    ]
