# Generated by Django 5.2.8 on 2026-01-26 08:18

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_install_vector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='idx_tx_embedding', opclasses=['vector_cosine_ops']),
        ),
    ]
