# Generated by Django 5.2.8 on 2026-01-26 09:43

import logging

from django.db import migrations

from processors.similarity_matcher import generate_embedding

logger = logging.getLogger(__name__)


def compute_embeddings(apps, schema_editor):
    Transaction = apps.get_model('api', 'Transaction')

    # Get all transactions that don't have an embedding yet
    queryset = Transaction.objects.filter(status='categorized', merchant__isnull=False,
                                          category__isnull=False, description__isnull=False, transaction_type='expense')

    total = queryset.count()
    if total == 0:
        return

    try:
        from processors.embeddings import EmbeddingEngine
    except ImportError:
        print("Could not import EmbeddingEngine. Skipping embedding computation.")
        return

    print(f"Computing embeddings for {total} transactions...")

    try:
        model = EmbeddingEngine.get_model()
    except Exception as e:
        print(f"Could not load embedding model: {e}")
        return

    batch_size = 100
    processed = 0

    # We use a list of IDs to process to avoid issues with the queryset changing
    # as we update the embedding field.
    all_ids = list(queryset.values_list('id', flat=True))

    for i in range(0, len(all_ids), batch_size):
        batch_ids = all_ids[i:i + batch_size]
        batch = list(Transaction.objects.filter(id__in=batch_ids))
        print(f"Processing batch starting at index {i}...")
        try:
            for tx in batch:
                # Match the logic used in SimilarityMatcherRAG
                tx.embedding = generate_embedding(description=tx.description)

            Transaction.objects.bulk_update(batch, ['embedding'])
            processed += len(batch)
            if processed % 500 == 0 or processed == total:
                print(f"Processed {processed}/{total} transactions...")
        except Exception as e:
            print(f"Error processing batch starting at index {i}: {e}")
            continue


def reverse_compute_embeddings(apps, schema_editor):
    Transaction = apps.get_model('api', 'Transaction')
    Transaction.objects.all().update(embedding=None)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0037_transaction_embedding_transaction_idx_tx_embedding'),
    ]

    operations = [
        migrations.RunPython(compute_embeddings, reverse_compute_embeddings),
    ]
