# Generated by Django 6.0.1 on 2026-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_compute_transaction_embeddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStructureMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_column_name', models.CharField(blank=True, help_text='The header name in the CSV that corresponds to the transaction description.', max_length=255, null=True)),
                ('income_amount_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True)),
                ('expense_amount_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction amount.', max_length=255, null=True)),
                ('date_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the transaction date.', max_length=255, null=True)),
                ('merchant_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the merchant or payee name.', max_length=255, null=True)),
                ('operation_type_column_name', models.CharField(blank=True, help_text='The header name in the CSV for the operation type.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Agent description of the csv structure')),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row_hash',), name='unique_user_transaction_row')],
            },
        ),
    ]
