# Generated by Django 6.0.1 on 2026-02-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_populate_filestructuremetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='upload_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.uploadfile'),
        ),
    ]
