# Generated by Django 6.0.1 on 2026-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_optional_transaction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manual_insert',
            field=models.BooleanField(default=False),
        ),
    ]
