# Generated by Django 6.0.1 on 2026-02-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_transaction_manual_insert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=70),
        ),
        migrations.DeleteModel(
            name='UploadResume',
        ),
    ]
