# Generated by Django 6.0.1 on 2026-02-15 19:31

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_uploadfile_status_delete_uploadresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_structure_metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_files', to='api.filestructuremetadata'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MerchantEMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_footprint', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_structure_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_emas', to='api.filestructuremetadata')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emas', to='api.merchant')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(fields=['digital_footprint'], name='merchant_ema_footprint_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
