# Generated by Django 6.0.1 on 2026-02-15 22:30

import hashlib
from django.db import migrations

def generate_tuple_hash(keys):
    """
    Mirror of FileStructureMetadata.generate_tuple_hash
    """
    sorted_keys = sorted(list(keys))
    data_payload = "|".join(sorted_keys)
    return hashlib.sha256(data_payload.encode('utf-8')).hexdigest()

def populate_file_structure_metadata(apps, schema_editor):
    UploadFile = apps.get_model('api', 'UploadFile')
    FileStructureMetadata = apps.get_model('api', 'FileStructureMetadata')
    Transaction = apps.get_model('api', 'Transaction')

    for upload_file in UploadFile.objects.all():
        # Try to find a transaction to get the original keys (headers)
        first_transaction = Transaction.objects.filter(upload_file=upload_file).first()
        
        if first_transaction and first_transaction.raw_data:
            keys = first_transaction.raw_data.keys()
            row_hash = generate_tuple_hash(keys)
        else:
            # Fallback to hashing the column names if no transaction exists
            column_names = [
                upload_file.description_column_name,
                upload_file.income_amount_column_name,
                upload_file.expense_amount_column_name,
                upload_file.date_column_name,
                upload_file.merchant_column_name,
                upload_file.operation_type_column_name,
            ]
            keys_to_hash = [str(v) for v in column_names if v]
            if not keys_to_hash:
                continue
            row_hash = generate_tuple_hash(keys_to_hash)
        
        fsm, created = FileStructureMetadata.objects.get_or_create(
            row_hash=row_hash,
            defaults={
                'description_column_name': upload_file.description_column_name,
                'income_amount_column_name': upload_file.income_amount_column_name,
                'expense_amount_column_name': upload_file.expense_amount_column_name,
                'date_column_name': upload_file.date_column_name,
                'merchant_column_name': upload_file.merchant_column_name,
                'operation_type_column_name': upload_file.operation_type_column_name,
                'notes': upload_file.notes or ''
            }
        )
        
        upload_file.file_structure_metadata = fsm
        upload_file.save(update_fields=['file_structure_metadata'])

def reverse_populate_file_structure_metadata(apps, schema_editor):
    UploadFile = apps.get_model('api', 'UploadFile')
    UploadFile.objects.all().update(file_structure_metadata=None)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_uploadfile_file_structure_metadata_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_file_structure_metadata, reverse_populate_file_structure_metadata),
    ]
