# Generated by Django 6.0.1 on 2026-02-15 19:49

from django.db import migrations

def generate_merchant_ema(apps, schema_editor):
    import numpy as np
    Transaction = apps.get_model('api', 'Transaction')
    MerchantEMA = apps.get_model('api', 'MerchantEMA')
    
    # We only care about transactions that have all needed components
    # We order by merchant, file structure, and date to apply EMA correctly
    transactions = Transaction.objects.filter(
        merchant__isnull=False,
        embedding__isnull=False,
        upload_file__file_structure_metadata__isnull=False
    ).order_by(
        'merchant_id', 
        'upload_file__file_structure_metadata_id',
        'transaction_date',
        'created_at'
    ).values_list(
        'merchant_id', 
        'upload_file__file_structure_metadata_id', 
        'embedding'
    )

    current_group = None
    current_ema = None
    
    emas_to_create = []
    
    for merchant_id, fsm_id, embedding in transactions.iterator():
        if embedding is None:
            continue
            
        group = (merchant_id, fsm_id)
        embedding_vec = np.array(embedding)
        
        if group != current_group:
            if current_group is not None:
                emas_to_create.append(
                    MerchantEMA(
                        merchant_id=current_group[0],
                        file_structure_metadata_id=current_group[1],
                        digital_footprint=current_ema.tolist()
                    )
                )
            
            current_group = group
            current_ema = embedding_vec
        else:
            # EMA formula: 0.9 * old + 0.1 * new
            current_ema = 0.9 * current_ema + 0.1 * embedding_vec
            
    # Add the last group
    if current_group is not None:
        emas_to_create.append(
            MerchantEMA(
                merchant_id=current_group[0],
                file_structure_metadata_id=current_group[1],
                digital_footprint=current_ema.tolist()
            )
        )
        
    if emas_to_create:
        # Clear any existing ones to avoid duplicates if migration is re-run (though RunPython is usually one-way)
        MerchantEMA.objects.all().delete()
        MerchantEMA.objects.bulk_create(emas_to_create)

def reverse_merchant_ema(apps, schema_editor):
    MerchantEMA = apps.get_model('api', 'MerchantEMA')
    MerchantEMA.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_uploadfile_file_structure_metadata_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_merchant_ema, reverse_merchant_ema),
    ]
