# Generated by Django 6.0.1 on 2026-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_generate_merchant_ema'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
