# Generated by Django 6.0.1 on 2026-02-17 14:24

from django.db import migrations


def update_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    # Use settings.SITE_NAME as the domain
    from django.conf import settings
    
    domain = settings.SITE_NAME
    name = "Pecuniam"
    
    # Update the default site (id=1)
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={'domain': domain, 'name': name}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_profile_welcome_email_sent'),
        ('sites', '0002_alter_domain_unique'), # Ensure sites is initialized
    ]

    operations = [
        migrations.RunPython(update_site),
    ]
