# Generated by Django 6.0.1 on 2026-02-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_update_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mock_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
