# Generated by Django 6.0.1 on 2026-02-18 08:08

from django.db import migrations


def populate_steps(apps, schema_editor):
    OnboardingStep = apps.get_model('api', 'OnboardingStep')
    steps_data = [
        {
            'step_number': 1,
            'title': 'Crea le tue Categorie',
            'description': 'Il primo passo è creare le categorie di spesa (es. Spesa, Affitto, Trasporti) con una breve descrizione.',
            'mock_type': 'categories'
        },
        {
            'step_number': 2,
            'title': 'Carica i tuoi Dati',
            'description': 'Ora carica il file CSV delle tue transazioni bancarie per iniziare a categorizzarle.',
            'mock_type': 'upload'
        },
        {
            'step_number': 3,
            'title': 'Usa i Filtri',
            'description': 'Ottimo! Ora puoi usare i filtri per analizzare le tue spese per periodo, categoria o esercente.',
            'mock_type': 'filters'
        },
        {
            'step_number': 4,
            'title': 'Personalizza le tue Spese',
            'description': 'Puoi cambiare la categoria di una spesa cliccando sulla "pillola" colorata, oppure cliccare sulla riga per vedere i dettagli.',
            'mock_type': 'modify'
        }
    ]
    for step in steps_data:
        OnboardingStep.objects.get_or_create(
            step_number=step['step_number'],
            defaults={
                'title': step['title'],
                'description': step['description'],
                'mock_type': step['mock_type']
            }
        )

def remove_steps(apps, schema_editor):
    OnboardingStep = apps.get_model('api', 'OnboardingStep')
    OnboardingStep.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_onboardingstep'),
    ]

    operations = [
        migrations.RunPython(populate_steps, remove_steps),
    ]
