# Generated by Django 6.0.1 on 2026-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_populate_onboarding_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_no_category_modal',
            field=models.BooleanField(default=True),
        ),
    ]
