# Generated by Django 6.0.1 on 2026-02-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_profile_show_no_category_modal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_no_category_modal',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
