# Generated by Django 6.0.1 on 2026-02-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_profile_show_no_category_modal_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='trans_merch_raw_trgm_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failure_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_raw_name',
        ),
    ]
