# Generated by Django 6.0.1 on 2026-02-19 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_transaction_trans_merch_raw_trgm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='encrypted_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='name_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='encrypted_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='encrypted_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL),
        ),
    ]
