# Generated by Django 6.0.1 on 2026-02-19 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_populate_merchant_privacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='merchant',
            name='api_merchan_user_id_83401b_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchant',
            name='api_merchan_user_id_b93138_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchant',
            name='merchant_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchant',
            name='merchant_norm_name_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['user', 'name_hash'], name='api_merchan_user_id_0d991a_idx'),
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='normalized_name',
        ),
    ]
