# Generated by Django 6.0.1 on 2026-02-19 20:54

from django.conf import settings
from django.db import migrations, models
from api.privacy_utils import encrypt_value, generate_blind_index


def populate_transaction_privacy_fields(apps, schema_editor):
    Transaction = apps.get_model('api', 'Transaction')
    for tx in Transaction.objects.all():
        # amount and description are still available here as they are in the model's state
        if hasattr(tx, 'amount') and tx.amount is not None:
            tx.encrypted_amount = encrypt_value(tx.amount)
        if hasattr(tx, 'description') and tx.description:
            tx.encrypted_description = encrypt_value(tx.description)
            tx.description_hash = generate_blind_index(tx.description)
        tx.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_drop_merchant_plaintext_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS user_financial_summary CASCADE;"),
        migrations.RunSQL("DROP VIEW IF EXISTS monthly_financial_summary CASCADE;"),
        migrations.RunSQL("DROP VIEW IF EXISTS category_monthly_summary CASCADE;"),
        migrations.RunSQL("DROP VIEW IF EXISTS internal_bank_transfer CASCADE;"),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_user_id_2c29bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trans_desc_trgm_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'description_hash'], name='api_transac_user_id_bcf47f_idx'),
        ),
        migrations.RunPython(populate_transaction_privacy_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='normalized_description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reasoning',
        ),
    ]
