# Generated by Django 6.0.1 on 2026-02-19 21:16

from django.db import migrations, models
from api.privacy_utils import decrypt_value
from decimal import Decimal

def decrypt_amounts(apps, schema_editor):
    Transaction = apps.get_model('api', 'Transaction')
    for tx in Transaction.objects.all():
        if tx.encrypted_amount:
            val = decrypt_value(tx.encrypted_amount)
            if val:
                try:
                    tx.amount = Decimal(val)
                    tx.save()
                except Exception:
                    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_add_description_hash_and_drop_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(decrypt_amounts, migrations.RunPython.noop),
    ]
