# Generated by Django 6.0.1 on 2026-02-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_add_amount_back_to_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='encrypted_amount',
        ),
    ]
