# Generated by Django 6.0.1 on 2026-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_drop_encrypted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='encrypted_amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
