# Generated by Django 6.0.1 on 2026-02-19 21:27

from django.db import migrations
from api.privacy_utils import encrypt_value

def encrypt_existing_amounts(apps, schema_editor):
    Transaction = apps.get_model('api', 'Transaction')
    for tx in Transaction.objects.all():
        if tx.amount is not None:
            tx.encrypted_amount = encrypt_value(str(tx.amount))
            tx.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_add_encrypted_amount'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_amounts, migrations.RunPython.noop),
    ]
