# Generated by Django 6.0.1 on 2026-02-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_populate_encrypted_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
