# Generated by Django 6.0.1 on 2026-02-25 12:30

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_drop_amount_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='name_new',
            field=api.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_new',
            field=api.fields.EncryptedDecimalField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description_new',
            field=api.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]