# Generated by Django 6.0.1 on 2026-02-25 12:35

from django.db import migrations


def migrate_encrypted_data(apps, schema_editor):
    # Use raw SQL to copy data directly from the physical columns
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # Copy Merchant.encrypted_name -> Merchant.name_new
        cursor.execute("""
                       UPDATE api_merchant
                       SET name_new = encrypted_name
                       WHERE encrypted_name IS NOT NULL
                       """)

        # Copy Transaction.encrypted_amount -> Transaction.amount_new
        cursor.execute("""
                       UPDATE api_transaction
                       SET amount_new = encrypted_amount
                       WHERE encrypted_amount IS NOT NULL
                       """)

        # Copy Transaction.encrypted_description -> Transaction.description_new
        cursor.execute("""
                       UPDATE api_transaction
                       SET description_new = encrypted_description
                       WHERE encrypted_description IS NOT NULL
                       """)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0068_add_temporary_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_encrypted_data, reverse_code=migrations.RunPython.noop),
    ]