# Generated by Django 6.0.1 on 2026-02-25 12:40

import api.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0069_migrate_encrypted_fields'),
    ]

    operations = [
        # Drop the old physical columns
        migrations.RunSQL(
            sql="ALTER TABLE api_merchant DROP COLUMN IF EXISTS encrypted_name",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_transaction DROP COLUMN IF EXISTS encrypted_amount",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_transaction DROP COLUMN IF EXISTS encrypted_description",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Rename the _new columns to encrypted_* (NOT just name/amount/description!)
        migrations.RunSQL(
            sql="ALTER TABLE api_merchant RENAME COLUMN name_new TO name",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_transaction RENAME COLUMN amount_new TO amount",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_transaction RENAME COLUMN description_new TO description",
            reverse_sql=migrations.RunSQL.noop,
        )
    ]