# Generated by Django 6.0.1 on 2026-02-25 12:03

import api.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_finalize_encrypted_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyMonthlyUserRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_year', models.IntegerField()),
                ('total_amount_expense_by_year', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('total_amount_income_by_year', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('total_amount_expense_by_month', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('total_amount_income_by_month', api.fields.EncryptedDecimalField(blank=True, null=True)),
                ('month_number', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_rollups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yearly Monthly User Rollup',
                'verbose_name_plural': 'Yearly Monthly User Rollups',
                'unique_together': {('user', 'by_year', 'month_number')},
            },
        ),
        migrations.DeleteModel(
            name='CategoryMonthlySummary',
        ),
        migrations.DeleteModel(
            name='MonthlySummary',
        ),
        migrations.DeleteModel(
            name='UserFinancialSummary',
        ),
    ]
