# Generated by Django 6.0.1 on 2026-02-25 19:15

import api.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_yearlymonthlyuserrollup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='merchant',
            name='fuzzy_search_trigrams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fuzzy_search_trigrams'], name='api_merchan_fuzzy_s_342e37_gin'),
        ),
    ]
