# Generated by Django 5.2.8 on 2026-01-07 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0025_delete_internalbanktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='e.g., gemini-2.5-flash-lite', max_length=100, unique=True)),
                ('input_token_price_per_million', models.DecimalField(decimal_places=4, help_text='Price in USD for 1 million input tokens', max_digits=10)),
                ('output_token_price_per_million', models.DecimalField(decimal_places=4, help_text='Price in USD for 1 million output tokens', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('computed_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('upload_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to='api.csvupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
