# Generated by Django 5.2.8 on 2026-01-07 20:07

from django.db import migrations


def add_default_cost_config(apps, schema_editor):
    CostConfiguration = apps.get_model('costs', 'CostConfiguration')
    CostConfiguration.objects.get_or_create(
        model_name='gemini-2.5-flash-lite',
        defaults={
            'input_token_price_per_million': 0.075,
            'output_token_price_per_million': 0.30,
            'is_active': True
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_cost_config),
    ]
