# Generated by Django 5.2.8 on 2026-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_auto_20260107_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costconfiguration',
            old_name='model_name',
            new_name='llm_model',
        ),
        migrations.AddField(
            model_name='costconfiguration',
            name='earning_multiplier_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Percentage of total cost to earn per token', max_digits=10),
        ),
        migrations.AddField(
            model_name='costconfiguration',
            name='minimum_earnings',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Minimum amount of earnings to be considered', max_digits=10),
        ),
    ]
