# Generated by Django 5.2.8 on 2026-01-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_rename_model_name_costconfiguration_llm_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusagelog',
            name='model_name',
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='cost_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costs.costconfiguration'),
        ),
    ]
