# Generated by Django 5.2.8 on 2026-01-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_remove_apiusagelog_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='final_earning',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='input_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='output_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
    ]
