# Generated by Django 5.2.8 on 2026-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_fix_apiusagelog_upload_file_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusagelog',
            name='final_earning',
        ),
        migrations.RemoveField(
            model_name='costconfiguration',
            name='earning_multiplier_percentage',
        ),
        migrations.RemoveField(
            model_name='costconfiguration',
            name='minimum_earnings',
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='number_of_transactions',
            field=models.IntegerField(default=0),
        ),
    ]
